### ISSUE TITLE
Linking this package links all other packages in react-native 0.55.4

### ISSUE THREAD

**Issue by cfmitrah** [Estimote/react-native-proximity#38]
when i run this command
```
react-native link @estimote/react-native-proximity
```
all other packages are linked instead of linking this specific package. this doesn't occur in newer versions of react native. how can i link this package in react-native:0.55.4?

**Comment by heypiotr** [comment]
I'm not entirely surely what you mean, but it sounds like a problem with `react-native link`. Maybe there was some bug in an older version of React? I __think__ there used to be some problems with the `@` sign.

For what it's worth though, I tried it and it worked for me:

```
$ react-native init LinkTestFiveFiveFour --version react-native@0.55.4 
...
$ cd LinkTestFiveFiveFour/
$ yarn add @estimote/react-native-proximity
...
$ react-native link @estimote/react-native-proximity
Scanning folders for symlinks in /Users/piotr/Downloads/LinkTestFiveFiveFour/node_modules (10ms)
rnpm-install info Linking @estimote/react-native-proximity ios dependency 
rnpm-install info Platform 'ios' module @estimote/react-native-proximity has been successfully linked 
rnpm-install info Linking @estimote/react-native-proximity android dependency 
rnpm-install info Platform 'android' module @estimote/react-native-proximity has been successfully linked
```

Here's the diff before the link and after the link, in case you want to manually recreate what link does:

https://gist.github.com/heypiotr/bb6d55233c225fc7ec069e7098d531bd

**Comment by cfmitrah** [comment]
```
D:\Projects\clap>react-native link @estimote/react-native-proximity
Scanning folders for symlinks in D:\Projects\clap\node_modules (16ms)
rnpm-install info Platform 'ios' module @estimote/react-native-proximity is already linked
rnpm-install info Linking @estimote/react-native-proximity android dependency
rnpm-install info Platform 'android' module @estimote/react-native-proximity has been successfully linked
rnpm-install info Platform 'ios' module instabug-reactnative is already linked
rnpm-install info Linking instabug-reactnative android dependency
rnpm-install info Platform 'android' module instabug-reactnative has been successfully linked
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn ruby ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
In the above logs you can see that instabug-reactnative is also getting linked along with this package

**Comment by heypiotr** [comment]
Yea, I don't understand why it's trying to link `instabug-reactnative` when you told it to link the `@estimote/react-native-proximity`. But all in all, it looks like the Estimote plugin got linked correctly and you can start using it. If you also want to resolve the problem with linking `instabug-reactnative`, maybe this issue will help: https://github.com/Instabug/Instabug-React-Native/issues/249
