### ISSUE TITLE
Build failure when compiling Android project

### ISSUE THREAD

**Issue by Walt-H** [Estimote/react-native-proximity#6]
After following the instructions in the project `README`, I encountered a problem when building the Android project via `react-native run-android` and Android Studios.

The following is the build output:
```
Executing tasks: [assemble]

Configuration on demand is an incubating feature.
Incremental java compilation is an incubating feature.
:@estimote/react-native-proximity:preBuild UP-TO-DATE
:@estimote/react-native-proximity:preDebugBuild UP-TO-DATE
:@estimote/react-native-proximity:checkDebugManifest
:@estimote/react-native-proximity:preDebugAndroidTestBuild UP-TO-DATE
:@estimote/react-native-proximity:preDebugUnitTestBuild UP-TO-DATE
:@estimote/react-native-proximity:preReleaseBuild UP-TO-DATE
:@estimote/react-native-proximity:preReleaseUnitTestBuild UP-TO-DATE
:@estimote/react-native-proximity:prepareAndroidArchCoreRuntime111Library UP-TO-DATE
:@estimote/react-native-proximity:prepareAndroidArchPersistenceDb110Library UP-TO-DATE
:@estimote/react-native-proximity:prepareAndroidArchPersistenceDbFramework110Library UP-TO-DATE
:@estimote/react-native-proximity:prepareAndroidArchPersistenceRoomRuntime110Library UP-TO-DATE
:@estimote/react-native-proximity:prepareAndroidArchPersistenceRoomRxjava2110Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComAndroidSupportAppcompatV72301Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComAndroidSupportSupportV42301Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteAnalyticsPlugin040Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteCloudPlugin100Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteInternalPluginsApi0220Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteKetchup050Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteProximitySdk061Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteRepositoryPlugin020Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComEstimoteScanningPlugin0200Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFbuiTextlayoutbuilderTextlayoutbuilder100Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoDrawee130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoFbcore130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoFresco130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoImagepipeline130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoImagepipelineBase130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookFrescoImagepipelineOkhttp3130Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookReactReactNative0554Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComFacebookSoloaderSoloader010Library UP-TO-DATE
:@estimote/react-native-proximity:prepareComWojtekWawerekAndroidSkald011Library UP-TO-DATE
:@estimote/react-native-proximity:prepareIoReactivexRxjava2Rxandroid201Library UP-TO-DATE
:@estimote/react-native-proximity:prepareOrgWebkitAndroidJscR174650Library UP-TO-DATE
:@estimote/react-native-proximity:prepareDebugDependencies
:@estimote/react-native-proximity:compileDebugAidl UP-TO-DATE
:@estimote/react-native-proximity:compileDebugNdk UP-TO-DATE
:@estimote/react-native-proximity:compileLint UP-TO-DATE
:@estimote/react-native-proximity:copyDebugLint UP-TO-DATE
:@estimote/react-native-proximity:compileDebugRenderscript UP-TO-DATE
:@estimote/react-native-proximity:generateDebugBuildConfig UP-TO-DATE
:@estimote/react-native-proximity:generateDebugResValues UP-TO-DATE
:@estimote/react-native-proximity:generateDebugResources UP-TO-DATE
:@estimote/react-native-proximity:mergeDebugResources UP-TO-DATE
:@estimote/react-native-proximity:processDebugManifest UP-TO-DATE
:@estimote/react-native-proximity:processDebugResources UP-TO-DATE
:@estimote/react-native-proximity:generateDebugSources UP-TO-DATE
:@estimote/react-native-proximity:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:@estimote/react-native-proximity:compileDebugJavaWithJavac
:@estimote/react-native-proximity:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:8: error: cannot find symbol
import com.estimote.proximity_sdk.proximity.ProximityAttachment;
                                           ^
  symbol:   class ProximityAttachment
  location: package com.estimote.proximity_sdk.proximity
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:170: error: cannot find symbol
    private WritableMap attachmentToMap(ProximityAttachment attachment) {
                                        ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:177: error: cannot find symbol
    private WritableArray attachmentsToArray(List<? extends ProximityAttachment> attachments) {
                                                            ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:122: error: cannot find symbol
                    .withOnChangeAction(new Function1<List<? extends ProximityAttachment>, Unit>() {
                                                                     ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:124: error: cannot find symbol
                        public Unit invoke(List<? extends ProximityAttachment> attachments) {
                                                          ^
  symbol: class ProximityAttachment
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:111: error: cannot find symbol
                    .withOnExitAction(new Function1<ProximityAttachment, Unit>() {
                                                    ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:113: error: cannot find symbol
                        public Unit invoke(ProximityAttachment attachment) {
                                           ^
  symbol: class ProximityAttachment
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:100: error: cannot find symbol
                    .withOnEnterAction(new Function1<ProximityAttachment, Unit>() {
                                                     ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:102: error: cannot find symbol
                        public Unit invoke(ProximityAttachment attachment) {
                                           ^
  symbol: class ProximityAttachment
/Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java:179: error: cannot find symbol
        for (ProximityAttachment attachment : attachments) {
             ^
  symbol:   class ProximityAttachment
  location: class RNEstimoteProximityModule
Note: /Users/walt/Documents/Side Projects/Impromptu/React/Impromptu/node_modules/@estimote/react-native-proximity/android/src/main/java/com/estimote/react/RNEstimoteProximityModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
10 errors
:@estimote/react-native-proximity:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':@estimote/react-native-proximity:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.
```

Lastly, here is the trace back:
```
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':@estimote/react-native-proximity:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:39)
	at org.gradle.api.internal.tasks.compile.incremental.IncrementalCompilationFinalizer.execute(IncrementalCompilationFinalizer.java:24)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:127)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more
```

Any ideas on how I may resolve this?

**Comment by Walt-H** [comment]
I misinterpreted the commit message "breaking changes!" for new changes and not code breaks due to updates.

I will close this and reopen if this problem persists in the next version.
